on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: tahsin.azurecr.io
        username: ${{ secrets.acr_tahsin_username }}
        password: ${{ secrets.acr_tahsin_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t tahsin.azurecr.io/tahsin:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push tahsin.azurecr.io/tahsin:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_tahsin_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep k8s-crc | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace k8s-crc`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: k8s-crc
        container-registry-url: tahsin.azurecr.io
        container-registry-username: ${{ secrets.acr_tahsin_username }}
        container-registry-password: ${{ secrets.acr_tahsin_password }}
        secret-name: tahsindockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: k8s-crc
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          tahsin.azurecr.io/tahsin:${{ github.sha }}
        imagepullsecrets: |
          tahsindockerauth
